# Problem 2
# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

from time import time
start = time()

fib0=0
fib1=1
fib2=2
sumeven=0

while True:
	if fib2%2==0:
		sumeven+=fib2
	fib0=fib2
	fib2+=fib1
	fib1=fib0
	if fib2>=4000000:
		break

print('The sum of the even-valued terms <4m = '+str(sumeven))

print('Finished: Time ', ((time()-start)*1000),'ms')

# The sum of the even-valued terms < 4m = 4613732
# Solve Time: 0.06937ms 04/12/18